GDSC-SWU/2023-Medisight-SolutionChallenge

main.spec
medisight/lib/page/search_result.dart
medisight/lib/screen/camera_screen.dart
medisight/lib/screen/shoot_qr.dart
medisight/pubspec.lock
medisight/pubspec.yaml

- 'google_mlkit_barcode_scanning' ML kit을 사용하여 기본카메라에 QR 스캐너 구현
- 바코드가 인식되지 않는다면 서버로 이미지를 보내야 하는데 해당 코드는 아직 구현되지 못함

MDS-74 feat: QR scanner 기능 구현

---

medisight/lib/screen/intro_page_1.dart
medisight/lib/screen/intro_page_2.dart
medisight/lib/screen/intro_page_3.dart
medisight/lib/screen/intro_page_4.dart
medisight/lib/screen/tuto_screen.dart
medisight/pubspec.yaml

MDS-67 튜토리얼 페이지 제작

---

medisight/lib/screen/theme_screen.dart
medisight/lib/theme/animated_toggle_button.dart
medisight/lib/theme/theme.dart
medisight/lib/theme/theme_provider.dart

- 테마 설정 페이지 작성
- 기본 테마 색상 및 text 지정

MDS-76 테마 설정 페이지

---

backend/routes/Search.js

- 키워드 검색을 통해 제품코드, 제품명, 제조사 정보를 반환
- 두 글자부터 사용 권장 (현재는 플러터에서 처리함)

MDS-70 직접 검색 API 구현

---

FastAPI/ML/positionguide.py
FastAPI/main.py

- 촬영 가이드 모델(pytorch, hands detection) 연결
- 이미지 파일을 받아 가이드 결과 문자열 반환
- **촬영 가이드 api는 플러터에서 qr/barcode 인식을 못했을 경우 호출됨**
- predict 폴더의 네이밍이 가변적이었던 문제를 수정하고 실행 플랫폼 별 경로가 깨지는 문제 수정

MDS-75 촬영 가이드 모델 fast api 구현

---

backend/app.js
backend/routes/Map.js

- `/place`: 근처 약국 검색
- 주차장과 같은 필요없는 데이터 제거
- `/route`: 길찾기 task
- 플러터 페이지를 고려하여 현재(now), 다음,(next) 다음다음(nextnext) task로 재가공
- `/route/coords`: 길찾기 지도뷰 좌표 모음
- 플러터 페이지를 고려하여 points와 linestrings 구조 재가공

MDS-84 지도 API 구현

---

medisight/lib/page/search_result.dart

- 파이어베이스 Firestore에서 사용자가 설정한 기저질환 정보 접근
- 의약품 주의사항에서 기저질환이 있는지 검색
- 해당하는 질환이 있을 경우 주의 알림 다이얼로그 발생

MDS-77 기저질환 알림 다이얼로그 구현

---

medisight/lib/page/search_result_content.dart
medisight/lib/podo/search_result_category.dart
medisight/lib/screen/shoot_qr.dart

- 검색 결과 페이지에서 각 카테고리 버튼을 누르면 진입하는 페이지
- **용법용량의 통 XML은 아직 파싱되지 않음**
- 촬영 인식 후 결과 페이지에 진입하도록 연결

MDS-45 검색 결과 상세 페이지 구현

---

medisight/android/app/src/main/AndroidManifest.xml
medisight/lib/screen/bottom_navi.dart

- bottom navi index num =1일시 google assistant 켜지도록 함

MDS-89 어시스턴트 연결

---

medisight/lib/screen/home_screen.dart

MDS-88 homeScreen ui 수정

---

medisight/lib/screen/bottom_navi.dart

MDS-90 어시스턴트 런타임 에러 해결

---

medisight/lib/screen/create_alarm.dart
medisight/lib/screen/shoot_medi.dart
medisight/lib/screen/shoot_period.dart
medisight/lib/screen/shoot_qr.dart

- 의약품 촬영, 유효기간 촬영 페이지에서 안내 문구 출력
- 유효기간 촬영 페이지에서 결과를 alert로 띄움 (alert가 띄워졌을 때 카메라 스캔이 동작 안 하게 구현)
- 알람 페이지에 유효기간 카메라(shoot_period) 연결 미완성
- 'isTuto'처럼 firestore에서 'isAlarm'을 불러올 예정 
- isAlarm에 따라서 촬영 페이지에서 들어간 카메라인지 알람 페이지에서 들어간 카메라인지 구별 후 각각의 작업 수행
(촬영 페이지 -> alert 띄움, 알람 페이지 -> 유효기간을 알람 페이지로 반환함)
(알람 추가 버튼을 클릭하여 알람 제작 페이지로 들어갔을 때는 올바르게 카메라로 라우팅하지만 만들어진 알람을 클릭하여 들어갓을 때는 카메라 페이지로 라우팅 되지 않는 오류 존재)

MDS-92 feat: 카메라 tts 연결

---

medisight/lib/screen/intro_page_1.dart
medisight/lib/screen/intro_page_2.dart
medisight/lib/screen/intro_page_3.dart
medisight/lib/screen/intro_page_4.dart

- 유튜브 build 주석처리
- 촬영/지도/알람/기타 편의 기능 설명 삽입

MDS-94 튜토리얼 텍스트 입력

---

medisight/lib/screen/camera_screen.dart
medisight/lib/screen/create_alarm.dart
medisight/lib/screen/medi_screen.dart
medisight/lib/screen/shoot_period.dart
medisight/lib/screen/update_alarm.dart

- PR #38 오류 및 미완성 부분 해결
알람 페이지에 유효기간 카메라(shoot_period) 연결 미완성
'isTuto'처럼 firestore에서 'isAlarm'을 불러올 예정
isAlarm에 따라서 촬영 페이지에서 들어간 카메라인지 알람 페이지에서 들어간 카메라인지 구별 후 각각의 작업 수행
(촬영 페이지 -> alert 띄움, 알람 페이지 -> 유효기간을 알람 페이지로 반환함)
(알람 추가 버튼을 클릭하여 알람 제작 페이지로 들어갔을 때는 올바르게 카메라로 라우팅하지만 만들어진 알람을 클릭하여 들어갓을 때는 카메라 페이지로 라우팅 되지 않는 오류 존재)
-> 해결

MDS-93 알람 유효기간 촬영 연결

---

medisight/lib/screen/map_route_screen.dart
medisight/lib/widget/route_instruction_widget.dart
medisight/lib/widget/route_map_widget.dart

- 정신사납고 GPS 오차가 심했던 지도 페이지의 성능 향상
- 좌회전 등 다음 인스트럭션이 일정 거리 내에 들어올 경우 추가 안내하도록 개선

MDS-95 지도 페이지 성능 개선

---

medisight/lib/page/home.dart
medisight/lib/screen/bottom_navi.dart
medisight/lib/screen/disease_select.dart
medisight/lib/screen/mypage_screen.dart

- 내비게이션바에 카메라 연결
- tts 오류 해결
- 마이페이지에서 기저질환 불러오기 -> 미완성 (주석처리)

MDS-100 feat: Add tts and Connect camera on navi

---

medisight/lib/page/home.dart
medisight/lib/screen/bottom_navi.dart
medisight/lib/screen/disease_select.dart
medisight/pubspec.lock
medisight/pubspec.yaml

- 내비게이션이 사라지는 버그 수정
- 내비게이션 탭 버튼 커스텀

MDS-103 Fix: 내비게이션 버그 수정 및 커스텀

---

medisight/lib/screen/map_route_screen.dart
medisight/lib/widget/route_instruction_widget.dart
medisight/lib/widget/route_map_widget.dart

- 요새 잠을 못자서 잘못 쓴 타이머 똥코드 수정
- 다음 인스트럭션이 10m 이내이면 다음 인스트럭션의 방향 아이콘을 표시하도록 수정

MDS-106 지도 페이지 라우팅 버그 패치

---

medisight/lib/screen/bottom_navi.dart
medisight/lib/screen/update_alarm.dart

- 알람 수정 페이지에서 dateList 초기화 오류 수정
- dispose로 controller들 닫는 코드 추가

MDS-115 알람 수정 페이지 오류 수정

---

medisight/lib/screen/bottom_navi.dart

- 내비게이션바가 키보드 위로 올라가는 에러 부분 해결

MDS-116 내비게이션바 에러 해결

---

medisight/lib/screen/shoot_qr.dart

MDS-120 촬영 시간 수정

---

backend/package-lock.json
backend/package.json
backend/util/Database.js
backend/util/OpenAPI.js

- Permission reqeust end point 변경에 따라 url 수정
- 대문자 수정으로 인한 TRUNCATE TABLE 명 변경
- 백엔드 버전 업데이트: 1.1.0 -> 1.1.1

MDS-122 [!HOTFIX] 백엔드 API end point 수정 및 쿼리 변경

---

backend/package-lock.json
backend/package.json
backend/util/Database.js
backend/util/OpenAPI.js

- 에러 핸들링 로직 변경 (statusCode로 구분하지 않음)
- 공공데이터 쪽에서 에러가 나도 200으로 보냄..
- 중간에 적재 실패해도 1회 재시도하며 재시도까지 실패할 시 스킵하고 다음 페이지를 적재하도록 수정
- 호출 제한에 걸리지 않도록 비동기 로직 수정
- 적재 직전에 해당 테이블을 truncate 하도록 수정
- 적재 현황을 알 수 있는 귀여운 로그 추가

MDS-122 [!HOTFIX] 공공데이터 에러 핸들링 및 비동기 패치
